### ISSUE TITLE
Request: Count unread from assigned (selected) inbox and/or sub-folder.

### ISSUE THREAD

**Issue by MvErven** [teleshoes/thunderbird-unread-count#6]
Hello, I have been looking for such an easy add-on for thunderbird.
The current version 0.0.4 works for me. 
As a helpdesk member I get a lot of mails from multiple adresses (senders) and multiple in-boxes. 
I've 40 "Message rules" which stores e-mails from users of cron jobs into sub-folders.

For example:

Inbox cronjobs has 9 sub folders. 
Each subfolder has a few items every hour. (This case, an automated import has run (or not))
If an subfolder contains x items at designated time, I want to trigger an alert!

I wanted to request the folowing: 
Be able to make a selection of inboxes of sub-folders to read, and create a file per inbox/sub-folder

Would this be possible? Or have you any other sugestions?

Kind regards.
Michiel.

**Comment by teleshoes** [comment]
im afraid that i stopped using thunderbird a couple of years ago, and so i wont be developing this addon except for simple routine maintenance for folks that use it.
iirc, your request should be feasible, though. if you implement it, id be happy to merge it here for others to use. sorry, and good luck!

**Comment by MvErven** [comment]
Thank you for the swift reply. I was a little afraid for this, looking at the stats of the issues and closed files.  However I'm not a skilled programmer. I'll have to try find something else. Maybe good old telnet or powershell.  Cheers, and take care. (case closed)
